variables:
  GIT_SSL_NO_VERIFY: 1

stages:
  - "build.source"
  - "apply.cors"

build:
  image: registry.soft-fx.lv/org/nodejs/node:18.5.0-alpine3.16-build
  stage: "build.source"
  script:
    - npm install
    - node node_modules/fxo-configuration/src/index.js --branch=${CI_COMMIT_REF_NAME}
    - npm run lint:fix
    - REACT_APP_BRANCH=${CI_COMMIT_REF_NAME} npm run build
    - s3cmd
      --host=${AWS_S3_HOST}
      --host-bucket=${CI_PROJECT_NAME}.${AWS_S3_HOST}
      --signature-v2
      --progress
      --no-preserve
      --recursive
      --force
      --acl-public
      --no-check-certificate
      --delete-removed
      --no-mime-magic
      --guess-mime-type
      sync ./build/ s3://${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}/

cors:
  image: registry.soft-fx.lv/org/s3tools/s3cmd:2.2.0
  stage: "apply.cors"
  script:
    - s3cmd
      --host=${AWS_S3_HOST}
      --host-bucket=${CI_PROJECT_NAME}.${AWS_S3_HOST}
      --progress
      --force
      --no-check-certificate
      setcors corsrules.xml s3://${CI_PROJECT_NAME}
